<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Fitnet.Passes.Domain\Fitnet.Passes.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="UseCases\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
    </ItemGroup>

</Project>
