<Project Sdk="Microsoft.NET.Sdk.Web">
    
    <PropertyGroup>
      <UserSecretsId>90cc6bd5-351d-43ab-ba24-41bef6620dc9</UserSecretsId>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.66" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
        <PackageReference Include="MediatR" Version="14.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.4.1" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
        <PackageReference Update="SonarAnalyzer.CSharp" Version="10.15.0.120848" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="EvolutionaryArchitecture.Fitnet.UnitTests" />
        <InternalsVisibleTo Include="EvolutionaryArchitecture.Fitnet.IntegrationTests" />
        <InternalsVisibleTo Include="EvolutionaryArchitecture.Fitnet.ArchitectureTests" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="EvolutionaryArchitecture.Fitnet.IntegrationTests" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\Docs\Contracts\Api\Contracts.http">
        <Link>Contracts.http</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Common\" />
      <Folder Include="Passes\MarkPassAsExpired\Events\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Fitnet.Common\Fitnet.Common.csproj" />
      <ProjectReference Include="..\Fitnet.Passes.Contracts\Fitnet.Passes.Contracts.csproj" />
      <ProjectReference Include="..\Fitnet.Passes.Presentation\Fitnet.Passes.Presentation.csproj" />
    </ItemGroup>
  
</Project>